name: Update Watchlist

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          apt update && apt install git
          git checkout runewatch
          bash scripts/update_watchlist.sh
